import { Document, Packer, Paragraph, AlignmentType, HeadingLevel } from "docx"
import path from "node:path"
import fs from "node:fs/promises"
import { app } from "electron"

const HEADING_RE = /^(\d+(\.\d+)*\.?\s+\S|[A-Z][A-Z0-9 \-,'\u00C0-\u017F]{3,}$|^[A-Z]\.\s)/

export async function buildDocxFromText(text: string, title: string): Promise<Buffer> {
  const lines = text.replace(/\r\n/g, "\n").split("\n")
  const blocks: string[] = []
  let current: string[] = []
  for (const raw of lines) {
    const line = raw.replace(/\s+$/, "")
    if (line.trim() === "") {
      if (current.length > 0) {
        blocks.push(current.join(" ").replace(/\s+/g, " ").trim())
        current = []
      }
    } else {
      current.push(line.trim())
    }
  }
  if (current.length > 0) blocks.push(current.join(" ").replace(/\s+/g, " ").trim())

  const children: Paragraph[] = []
  for (const block of blocks) {
    if (!block) continue
    const isHeading = HEADING_RE.test(block) && block.length < 100
    if (isHeading) {
      children.push(
        new Paragraph({
          text: block,
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 200, after: 100 }
        })
      )
    } else {
      children.push(
        new Paragraph({
          text: block,
          spacing: { after: 120 },
          alignment: AlignmentType.JUSTIFIED
        })
      )
    }
  }

  if (children.length === 0) {
    children.push(new Paragraph({ text: text.trim() || "(empty)" }))
  }

  const doc = new Document({
    creator: "Clauly",
    title,
    description: "Generated by Clauly for live contract review.",
    sections: [{ properties: {}, children }]
  })
  return await Packer.toBuffer(doc)
}

export function contractStorageDir(): string {
  return path.join(app.getPath("userData"), "contracts")
}

export async function ensureContractDir(): Promise<string> {
  const dir = contractStorageDir()
  await fs.mkdir(dir, { recursive: true })
  return dir
}

export function sanitizeBaseName(filename: string): string {
  const base = path.basename(filename, path.extname(filename))
  const cleaned = base.replace(/[^a-zA-Z0-9_\-\u00C0-\u017F]+/g, "_").replace(/^_+|_+$/g, "")
  return cleaned || "contract"
}

export function targetDocxPath(filename: string): string {
  return path.join(contractStorageDir(), `${sanitizeBaseName(filename)}.docx`)
}
